version: '2'

services:
    web:
        build: .
        depends_on:
            - mysql
        links:
            - mysql
        volumes:
            - ./src:/var/www/html
            - ./mnt/logs:/var/www/logs
            - ./mnt/php/php.ini:/usr/local/etc/php/php.ini
            - ./mnt/apache2/conf-enabled/vhosts.conf:/etc/apache2/conf-enabled/vhosts.conf
            - ./mnt/apache2/vhosts/:/etc/apache2/vhosts/
        ports:
            - ${WEB_PORT}:80
        restart: ${WEB_RESTART}

    mysql:
        image: mysql:5.6
        environment:
              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
              MYSQL_DATABASE: ${MYSQL_DATABASE}
              MYSQL_USER: ${MYSQL_USER}
              MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./mnt/mysql:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        restart: ${MYSQL_RESTART}
