version: '2'

services:
    web:
        build:
            context: ./web
        volumes:
            - ./web/html:/var/www/html

    mysql:
        volumes:
            - ./_data/mysql:/var/lib/mysql
