version: '2'

services:
    web:
        image: ${WEB_IMAGE}
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - ${WEB_PORT}:80
        restart: ${WEB_RESTART}

    mysql:
        image: mysql:5.6
        environment:
              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
              MYSQL_DATABASE: ${MYSQL_DATABASE}
              MYSQL_USER: ${MYSQL_USER}
              MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        restart: ${MYSQL_RESTART}
